### ISSUE TITLE
small typo in regex

### ISSUE THREAD

**Issue by orgua** [entorb/typonuketool#4]
https://github.com/entorb/typonuketool/blob/820593dc5dbd7a58bf474c2f639d9b3b3e07b761/subs.pl#L257C96-L257C96

typo \+2 -> \2+

offtopic: my proselint-dev-branch has now tnt-checks up to [L931](https://github.com/entorb/typonuketool/blob/main/subs.pl#L931). source is always tracked

**Comment by entorb** [comment]
Thanks! but shouldn't the fix be
`\+s\2` -> `\s+\2`

**Comment by orgua** [comment]
yes, sorry.

i also simplified tbe expressions for less computational overhead:

```python
items = [
    r"((?<!\\)\b\w+)\s+\1\b",  # ignores \EA EA
    r"(\b\w+\s+\w+\b)\s+\1\b",
    r"(\b\w+\s+\w+\s+\w+\b)\s+\1\b",
    r"(\b\w+\s+\w+\s+\w+\s+\w+\b)\s+\1\b",
]
```
tools like https://regex101.com/ show you metrics for that.
